        JSUB   SPTEST .CALL SPTEST SUBROUTINE
.THIS IS A COMMENT LINE
		.
		.
		.		IS THIS A COMMENT LINE?
SPTEST  LDX    ZERO	. SUBROUTINE TO WRITE STRLEN-BYTE RECORD TO DEVICE AF
SPLOOP  TD     SPDEV
        JEQ    SPLOOP
		LDCH   SPSTR, X	.LET THIS BE A COMMENT LINE
		WD     SPDEV
		TIX    STRLEN
		JLT    SPLOOP
		RSUB
		.
        .
		.

CLOOP   JSUB    RDREC

        LDA     LENGTH

        COMP    ZERO        
        JEQ     ENDFIL          
        JSUB    WRREC       
        J       CLOOP
ZERO    BYTE   0
SPDEV   BYTE   X'AF'
SPSTR   BYTE   C'This is a first string. HELLO WORLD!, RIGHT?!'
STRLEN  WORD   45
STR1    BYTE    C'TEST STRING'
FIRST	LDCH	X,BUFFER	
BUFFER	RESB	4096		
EOF	BYTE	C'EOF'  	
INPUT	BYTE	X'11'

